groups:
  - name: example-alerts
    rules:
      - alert: HighErrorRate
        expr: sum(rate(http_requests_total{status="500"}[5m])) by (job) / sum(rate(http_requests_total[5m])) by (job) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate for job {{ $labels.job }} is above 5% for 5 minutes."

      - alert: LowDiskSpace
        expr: node_filesystem_free{mountpoint="/"} / node_filesystem_size{mountpoint="/"} < 0.1
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Low disk space"
          description: "Free space on / is less than 10% for 15 minutes."
