global:
  smtp_smarthost: 'smtp.example.com:587'  # Specify your SMTP server and port
  smtp_from: 'alertmanager@example.com'  # From email address
  smtp_auth_username: 'your-username'    # SMTP authentication username
  smtp_auth_password: 'your-password'    # SMTP authentication password

route:
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
      - to: 'your-email@example.com'
